import {
  ActivityType,
  Goal,
  GoalActivity,
  GoalCategory,
  GoalCompletionType,
  NotificationRecurrence,
  UnlockConditionType,
} from "@/backend/shared";

export const DEFAULT_GOALS: Goal[] = [
  {
    id: "7b1cba82-218e-49c1-bdc9-72029ea2166b",
    slug: "goal-0",
    name: "Sample Goal 0",
    description: "Description for goal 0",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    tags: ["tag0", "growth"],
    author: { id: "user-1", name: "Default User" },
    createdAt: Date.parse("2025-05-11T08:00:00.000Z"),
    updatedAt: Date.parse("2025-05-11T08:00:00.000Z"),
    isPublic: true,
    version: 1,
    status: "published",
    completionType: GoalCompletionType.ACTIVITY,
    completionDate: undefined,
    defaultRecurrence: "daily",
    defaultScheduledTimes: ["08:00"],
    progress: { completedActivities: 0, totalActivities: 5, completed: false },
    meta: {},
    activities: [], // populated later
  },
  {
    id: "1f170f80-2c2b-4709-998f-f918af8a997f",
    slug: "goal-1",
    name: "Sample Goal 1",
    description: "Description for goal 1",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    tags: ["tag1", "growth"],
    author: { id: "user-1", name: "Default User" },
    createdAt: Date.parse("2025-05-11T08:00:00.000Z"),
    updatedAt: Date.parse("2025-05-11T08:00:00.000Z"),
    isPublic: true,
    version: 1,
    status: "published",
    completionType: GoalCompletionType.ACTIVITY,
    completionDate: undefined,
    defaultRecurrence: "daily",
    defaultScheduledTimes: ["08:00"],
    progress: { completedActivities: 0, totalActivities: 5, completed: false },
    meta: {},
    activities: [],
  },
  {
    id: "7a5d32cf-2247-4609-bd02-6eb9e29391e2",
    slug: "goal-2",
    name: "Sample Goal 2",
    description: "Description for goal 2",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.PRODUCTIVITY,
    tags: ["tag2", "growth"],
    author: { id: "user-1", name: "Default User" },
    createdAt: Date.parse("2025-05-11T08:00:00.000Z"),
    updatedAt: Date.parse("2025-05-11T08:00:00.000Z"),
    isPublic: true,
    version: 1,
    status: "published",
    completionType: GoalCompletionType.DATETIME,
    completionDate: "2025-06-10T08:00:00.000Z",
    defaultRecurrence: "daily",
    defaultScheduledTimes: ["08:00"],
    progress: { completedActivities: 0, totalActivities: 5, completed: false },
    meta: {},
    activities: [],
  },
];

export const DEFAULT_ACTIVITIES: GoalActivity[] = [
  {
    id: "56be78f4-c2ee-41e6-a6db-8a382b8cd261",
    slug: "activity-0-0",
    name: "Activity 0 for Goal 0",
    description: "A sample activity description.",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    notificationsEnabled: true,
    scheduledTimes: ["08:00"],
    recurrence: NotificationRecurrence.DAILY,
    completionPrompts: [],
    reliesOn: [],
    unlockCondition: UnlockConditionType.AFTER_COMPLETION,
    unlockParams: {},
    meta: {},
    type: ActivityType.GUIDED_ACTIVITY,
    steps: [
      {
        id: "9c2d2679-404f-4fd4-a07a-5e4b51146e16",
        slug: "step-0",
        content: "Step 0 content",
        instructionMedia: {
          type: "image",
          url: "https://example.com/media/0.png",
          altText: "Sample media 0",
          size: 1024,
        },
        duration: 60,
        durationType: "seconds",
      },
    ],
  },
  {
    id: "3d35b89b-058a-4f62-bbcb-d0f7751e4f6d",
    slug: "activity-0-1",
    name: "Activity 1 for Goal 0",
    description: "A sample activity description.",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    notificationsEnabled: true,
    scheduledTimes: ["08:00"],
    recurrence: NotificationRecurrence.DAILY,
    completionPrompts: [],
    reliesOn: [],
    unlockCondition: UnlockConditionType.AFTER_COMPLETION,
    unlockParams: {},
    meta: {},
    type: ActivityType.TASK_ACTIVITY,
    steps: [
      {
        id: "60cce660-5ef9-426b-8826-06f2f12e997f",
        slug: "task-step-1",
        content: "Task step 1 content",
        instructionMedia: {
          type: "image",
          url: "https://example.com/media/1.png",
          altText: "Sample media 1",
          size: 1024,
        },
      },
    ],
  },
  {
    id: "05558b9b-8a27-4966-8b0e-bc6e7ae80fe7",
    slug: "activity-0-2",
    name: "Activity 2 for Goal 0",
    description: "A sample activity description.",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    notificationsEnabled: true,
    scheduledTimes: ["08:00"],
    recurrence: NotificationRecurrence.DAILY,
    completionPrompts: [],
    reliesOn: [],
    unlockCondition: UnlockConditionType.AFTER_COMPLETION,
    unlockParams: {},
    meta: {},
    type: ActivityType.GUIDED_ACTIVITY,
    steps: [
      {
        id: "89cd71db-6c63-4c4d-898f-988f8e0e9de4",
        slug: "step-2",
        content: "Step 2 content",
        instructionMedia: {
          type: "image",
          url: "https://example.com/media/2.png",
          altText: "Sample media 2",
          size: 1024,
        },
        duration: 60,
        durationType: "seconds",
      },
    ],
  },
  {
    id: "cf38ff4a-4cfd-4b68-92fc-6e4c8f4ac9ae",
    slug: "activity-0-3",
    name: "Activity 3 for Goal 0",
    description: "A sample activity description.",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    notificationsEnabled: true,
    scheduledTimes: ["08:00"],
    recurrence: NotificationRecurrence.DAILY,
    completionPrompts: [],
    reliesOn: [],
    unlockCondition: UnlockConditionType.AFTER_X_DAYS,
    unlockParams: {},
    meta: {},
    type: ActivityType.TASK_ACTIVITY,
    steps: [
      {
        id: "30b0ef72-d6b0-4ea4-9d7a-0737a04fa02f",
        slug: "task-step-3",
        content: "Task step 3 content",
        instructionMedia: {
          type: "image",
          url: "https://example.com/media/3.png",
          altText: "Sample media 3",
          size: 1024,
        },
      },
    ],
  },
  {
    id: "e58a3197-06b3-45f2-bdb2-11269a5a7340",
    slug: "activity-0-4",
    name: "Activity 4 for Goal 0",
    description: "A sample activity description.",
    featuredImage: "https://example.com/image.png",
    category: GoalCategory.SELF_CARE,
    notificationsEnabled: true,
    scheduledTimes: ["08:00"],
    recurrence: NotificationRecurrence.DAILY,
    completionPrompts: [],
    reliesOn: [],
    unlockCondition: UnlockConditionType.AFTER_X_DAYS,
    unlockParams: {},
    meta: {},
    type: ActivityType.GUIDED_ACTIVITY,
    steps: [
      {
        id: "6c8858c6-60d7-4555-bec2-dfc1866843df",
        slug: "step-4",
        content: "Step 4 content",
        instructionMedia: {
          type: "image",
          url: "https://example.com/media/4.png",
          altText: "Sample media 4",
          size: 1024,
        },
        duration: 60,
        durationType: "seconds",
      },
    ],
  },
];
